### ISSUE TITLE
media query

### ISSUE THREAD

**Issue by suganyaaliassanusha** [Mange/roadie-rails#23]
I am designing a mailer and I have two different stylesheets. one for desktop and one for mobile.
I have included roadie-rails gem in my gemfile.
In my layout file I have

 link rel="stylesheet" type="text/css" href="/assets/mailers_template/mailers_layout/mailers_template_desktop.css" 
  link rel="stylesheet" type="text/css" href="/assets/mailers_template/mailers_layout/mailers_template_mobile.css" data-immutable 

But still when my mail is delivered, I could see my media query overrides the native styles.

What should I do so that my media query works for devices and native styles for desktop?

**Comment by levelone** [comment]
Hi @Mange,

I seem to have stumbled upon this exact same problem. Having 2 separate css files both pointing to my email template..

My concern is that 'data-roadie-ignore' completely ignores the css file and doesn't consider the media query. Without it, media query overrides the native styles just like @suganyaaliassanusha.

Reference:
**email_layout.html.haml** - https://gist.github.com/levelone/d570362b86ac3c9eafe6
**email_layout_mobile.css** - https://gist.github.com/levelone/6439466326c0c2b19406
**email_layout_web.css** - https://gist.github.com/ff416eedb7ab495848b8

**Comment by Mange** [comment]
Your problem might depend on a whole lot of different things. First, how do you expect these media queries to work? Are you talking about them not being applied in your email, or is it some web version of the same view – e.g. not an email at all?

## Debugging ##

**Email**

Which client are you using? Are you sure it's even downloading the stylesheet? If you added something to it that didn't depend on media queries, and that doesn't collide with the rest of the styles does it get applied?

Here's an example:
```css
@media screen and (min-device-width: 600px) { 
  /* ... */
  html body.email-body { color: red !important; } /* Super specific omg */
  .header { border: 5px solid red; } /* Completely unrelated style */
}

/* Same rules but other colors to rule out @media problems */
html body.email-body { color: blue !important; }
.header { border: 5px solid blue; }

/*
If you see blue in the email, it's downloading the file but not applying @media rules;
if you see red everything works and the problem is with specificity fighting;
if you see neither, the stylesheet is not downloaded by the email client
*/
```

It's generally unusual for email clients to download external assets, and it's also very uncommon to support media queries.

**Web page**

That would most likely be a specificity issue. I see you already have `!important` on all of the styles, so you'd have to debug it in a browser. Inspect an element and look at the styled applied to it. Your media query styles should be there, but might be below "element styles". In that case, it's not "important enough". I have no good idea on how to fix that case.

## Fixing ##

**Email** – you can fix this by embedding a `style` element instead:

```haml
%head
  :css
    @media screen and (min-device-width: 600px) { 
      .header {
        background: #134F72 !important;
        text-align: left !important;
      }
    
      .email-container {
        padding: 40px 0 !important;
        width: 600px !important;
      }
    }
```

**Web page**

Sorry, mate. I don't know.
